const watchlistData = {
  "bonds": [
    {"symbol":"UST10Y","name":"US 10-Year Treasury","market":"Treasury"},
    {"symbol":"UST30Y","name":"US 30-Year Treasury","market":"Treasury"},
    {"symbol":"UST5Y","name":"US 5-Year Treasury","market":"Treasury"},
    {"symbol":"TLT","name":"iShares 20+ Year Treasury ETF","market":"ETF"},
    {"symbol":"IEI","name":"iShares 3-7 Year Treasury ETF","market":"ETF"},
    {"symbol":"BIV","name":"Vanguard Total Bond Market ETF","market":"ETF"},
    {"symbol":"SCHZ","name":"Schwab U.S. Aggregate Bond ETF","market":"ETF"},
    {"symbol":"LQD","name":"iShares iBoxx $ Investment Grade Corporate Bond ETF","market":"ETF"},
    {"symbol":"VCIT","name":"Vanguard Intermediate-Term Corporate Bond ETF","market":"ETF"},
    {"symbol":"BND","name":"Vanguard Total Bond Market ETF","market":"ETF"}
  ],
  "crypto": [
    {"symbol":"BTC","name":"Bitcoin","market":"Spot"},
    {"symbol":"ETH","name":"Ethereum","market":"Spot"},
    {"symbol":"USDT","name":"Tether","market":"Stablecoin"},
    {"symbol":"USDC","name":"USD Coin","market":"Stablecoin"},
    {"symbol":"BNB","name":"BNB","market":"Exchange Token"},
    {"symbol":"XRP","name":"XRP","market":"Spot"},
    {"symbol":"ADA","name":"Cardano","market":"Spot"},
    {"symbol":"SOL","name":"Solana","market":"Spot"},
    {"symbol":"DOGE","name":"Dogecoin","market":"Spot"},
    {"symbol":"DOT","name":"Polkadot","market":"Spot"}
  ],
  "stocks": [
    {"symbol":"ENR","name":"Siemens Energy","market":"EUR","theme":"Energy","category":"Gas"},
    {"symbol":"8058.T","name":"Mitsubishi Corporation","market":"TSE","theme":"AI","category":"Industrial Diodes","role":"Industrial/Telecom High-Power Laser Diodes (EML/DML)","edge":"The company has accumulated industrial-grade reliability references such as wavelength stability even under high-temp conditions"},
    {"symbol":"EXE","name":"Expand Energy Corp","market":"NASDAQ","theme":"Energy","category":"Gas"},
    {"symbol":"EQT","name":"EQT Corp","market":null,"theme":"Energy","category":"Gas"},
    {"symbol":"LNG","name":"Cheniere Energy","market":"NYSE","theme":"Energy","category":"Gas"},
    {"symbol":"WMB","name":"The WIlliams Company","market":"NYSE","theme":"Energy","category":"Gas"},
    {"symbol":"CCJ","name":"Cameco Corporation","market":"NYSE","theme":"Energy","category":"Uranium"},
    {"symbol":"LEU","name":"Centrus Energt Corp","market":"NYSE","theme":"Energy","category":"Uranium"},
    {"symbol":"NEE","name":"NextEra Energy Inc","market":"NYSE","theme":"Energy","category":"General Infra","edge":"Glossary"},
    {"symbol":"CSIQ","name":"Canadian Solar Inc","market":"NASDAQ","theme":"Energy","category":"Solar","edge":"TSE = Tokyo Stock Exchange"},
    {"symbol":"FSLR","name":"First Solar","market":"NASDAQ","theme":"Energy","category":"Solar"},
    {"symbol":"JKS","name":"JinkoSolar","market":"NYSE","theme":"Energy","category":"Solar"},
    {"symbol":"TE","name":"T1 Energy Inc","market":"NYSE","theme":"Energy","category":"Solar Supply Chain"},
    {"symbol":"NXT","name":"Nextpower Inc","market":"NASDAQ","theme":"Energy","category":"Solar"},
    {"symbol":"CATL","name":"Contemporary Amperex","market":"Shenzen","theme":"Energy","category":"Batteries"},
    {"symbol":"1211","name":"BYD Company Limited","market":"Hong Kong","theme":"Energy","category":"EV"},
    {"symbol":"373220","name":"LG Energy Solution","market":"Korea","theme":"Energy","category":"General Infra"},
    {"symbol":"FLNC","name":"Fluence Energy","market":null,"theme":"Energy","category":"General Infra"},
    {"symbol":"TSLA","name":"Tesla","market":null,"theme":"Energy","category":"General Infra"},
    {"symbol":"ETN","name":"Eaton Corporation","market":null,"theme":"Energy","category":"Components"},
    {"symbol":"SU","name":"Schneider Electric","market":null,"theme":"Energy","category":"General Infra"},
    {"symbol":"POWL","name":"Powell Industries","market":null,"theme":"Energy","category":"General Infra"},
    {"symbol":"PWR","name":"Quanta Services","market":null,"theme":"Energy","category":"Nuclear Infrastructure"},
    {"symbol":"SOLS","name":"Solstice Advanced Materials","market":null,"theme":"Energy","category":"Nuclear"},
    {"symbol":"SLX.AXS","name":"Silex Systems","market":"Australian","theme":"Energy","category":"Nuclear"},
    {"symbol":"034020.KS","name":"DooSan Enerbility","market":"Korea","theme":"Energy","category":"Nuclear"},
    {"symbol":"EQT","name":"EQT Corp","market":"NYSE","theme":"Energy","category":"Natgas"},
    {"symbol":"BE","name":"Bloom Energy Corp","market":"NYSE","theme":"Energy","category":"Storage"},
    {"symbol":"OKLO","name":"Oklo","market":"NYSE","theme":"Energy","category":"Nuclear"},
    {"symbol":"ONDS","name":"Ondas Inc","market":"NASDAQ","theme":"Defense","category":"Defense"},
    {"symbol":"BWXT","name":"BWX Technologies","market":"NYSE","theme":"Defense","category":"Defense"},
    {"symbol":"SMR","name":"Nuscale Power Corporation","market":"NYSE","theme":"Energy","category":"Nuclear"},
    {"symbol":"NEM","name":"NewMont Mining Corp","market":"NYSE","theme":"Metals","category":"Gold"},
    {"symbol":"DNN","name":"Dension Mines Corp","market":"NYSE","theme":"Metals","category":"Uranium"},
    {"symbol":"URNM","name":"Sprott Uranium Minerals","market":"NYSE","theme":"Metals","category":"Uranium"},
    {"symbol":"NXE","name":"NexGen Energy Ltd.","market":null,"theme":"Metals","category":"Uranium"},
    {"symbol":"UEC","name":"Uranium Energy Corp.","market":null,"theme":"Metals","category":"Uranium"},
    {"symbol":"URG","name":"Ur-Energy Inc","market":null,"theme":"Metals","category":"Uranium"},
    {"symbol":"UROY","name":"Uranium Royalty Corp","market":null,"theme":"Metals","category":"Uranium"},
    {"symbol":"UUUU","name":"Energy Fuels Inc","market":null,"theme":"Energy","category":"Uranium"},
    {"symbol":"ASML","name":"ASML Holding N.V","market":"NASDAQ","theme":"AI","category":"Chips"},
    {"symbol":"APLD","name":"Applied Digital Corp","market":"NASDAQ","theme":"AI","category":"Infra"},
    {"symbol":"MRVL","name":"Marvell Technology","market":"NASDAQ","theme":"AI","category":"Chips"},
    {"symbol":"NVDA","name":"Nvidia","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"AVGO","name":"Broadcom","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"XPEV","name":"Xpeng INc","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"LITE","name":"Lumentum Holdings","market":null,"theme":"AI","category":"Chips","edge":"Google Supplier"},
    {"symbol":"CIEN","name":"Ciena Corporation","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"LUMN","name":"Lumen Technologies","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"VRT","name":"Vertiv Holdings Co","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"5210.T","name":"Yamamura","market":"TYO","theme":"AI","category":"Fiber Optics"},
    {"symbol":"3816.HK","name":"KFM Kingdom Holdings","market":"Hong Kong","theme":"AI","category":"Chips","role":"Precision metal stamping manufacturer","edge":"Sell small metal parts/components used in products across network & data storage,office automation and consumer electronics across supply chains."},
    {"symbol":"300308.SZ","name":"Zhongji Innolight","market":null,"theme":"AI","category":"Chips","role":"Core supplier of high quality InP wafers","edge":"Lasers for high-speed data transmisson require secial compound substrates like InP. Demand for high-quality wafers rises as speed increases but yield and certification hurdles make it difficult for new entrants to penetrate the supply chain."},
    {"symbol":"6239.TW","name":"Powertech Technology","market":null,"theme":"AI","category":"Chips","role":"Ceramic packages and Heatsinks","edge":"accumulated extensive industrial references in Hermetic Sealing packaging and heat-dissipating ceramic materials/parts"},
    {"symbol":"AMKR","name":"Amkor Technology","market":null,"theme":"AI","category":"Chips","role":"High-performance Optical Sensors (PD) and Precision Metrology","edge":"Converting light signals back into data becomes exponentially more difficult regarding noise,temperature and packaging variables as speeds increase. HP is known for its InGaAs sensor lineup and a strong track record in precicion sensors."},
    {"symbol":"ASX","name":"ASE Tech Holdings","market":null,"theme":"AI","category":"Chips","role":"FC-BGA(High performance semiconductor packaging substrates","edge":"Chips can only deliver performance when supported by high-layer-count,fine-circuit substrates that handle power and signals. High-spec FC-BGA is not an item where capacity is added due to yield, tech and lead times bottlenecks. As AI server expansion race continues , this subsector is positioned to receive direct benefits."},
    {"symbol":"AXTI","name":"AXT Inc","market":null,"theme":"AI","category":"Chips","role":"Leader in Precision DIcing and Grinding Equipement","edge":"InP wafers and highly integrated semis are vulnerable to damage. As processes become more advanced, the presence of equipment companies that protect yield grows significantly,"},
    {"symbol":"SMTOY","name":"Sumitomo Electric Industries","market":null,"theme":"AI","category":"Wafers","role":"Ultra-high-speed telecoment measurement and test solutions","edge":"Moving toward next-gen speed standards, the ability to accurately measure metrics like BER (Bit Error Rate) and reproduce/isolate the causes of issues becomes critical. This field is a ‘learning industry’ where experience in participating in standardization and development stages accumulates.  In transition periods (e.g., 800G → 1.6T), the R&D/verification demand to \"find out why it's not working\" spikes first. Even if mass production of 1.6T is delayed, measurement demand can persist for a long time."},
    {"symbol":"KYOCY","name":"Kyocera","market":"TYO","theme":"AI","category":"Ceramic Packages and Heatsinks","role":"IOWN (All-Photonics Network) & Photo-Electronic Convergence Technology.","edge":"Rather than being an immediate component supplier, NTT is closer to an entity designing the standards and ecosystem, pushing for network/chip architectures that convert electrical signals to light. Investment Point: If data center architecture shifts significantly around 2030, NTT should be viewed as a ‘long-term option’ rather than a ‘short-term earnings leverage’ play."},
    {"symbol":"6965","name":"Hamamatsu Photonics","market":"TYO","theme":"AI","category":"High-performance Optical Sensors and Precision Metrology"},
    {"symbol":"4062","name":"Ibiden","market":"TYO","theme":"AI","category":"Substrates"},
    {"symbol":"6146","name":"DISCO","market":"TYO","theme":null,"category":"Processing Equipment"},
    {"symbol":"6754","name":"Anritsu","market":"TYO","theme":"AI","category":"Testing and Measurement"},
    {"symbol":"9432","name":"NTT","market":"TYO","theme":"AI","category":"Data"},
    {"symbol":"SNDK","name":"Sandisk Corp","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"000660.KS","name":"SK Hynix Inc","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"UMC","name":"United Microelectronics","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"MU","name":"Micron Technology","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"ACMR","name":"ACM Research Inc","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"0981.HK","name":"Semiconductor Manufacturing","market":null,"theme":"AI","category":"Chips"},
    {"symbol":"2513.HK","name":"Knowledge Atlas Tech Joint","market":"Hong Kong","theme":"AI","category":"Chips"},
    {"symbol":"PATH","name":"UiPATH","market":"NYSE","theme":"AI","category":"Chips"},
    {"symbol":"VERI","name":"Veriton","market":"NASDAQ","theme":"AI","category":"Robotics"},
    {"symbol":"2337.TW","name":"Macronix","market":null,"theme":"AI","category":"Storage"},
    {"symbol":"TSEM","name":"Tower Semiconductor","market":"NASDAQ","theme":"AI","category":"Semiconductor"},
    {"symbol":"GOOG","name":"Google","market":"NYSE","theme":"AI","category":"Software"},
    {"symbol":"SIMO","name":"Silicon Motion Technology Corporation","market":null,"theme":"AI","category":"Memory"},
    {"symbol":"LITE","name":"Lumentum Holdings","market":null,"theme":"AI","category":"Photonics"},
    {"symbol":"COHR","name":"Coherent Corp.","market":"EUR","theme":"AI","category":"Photonics"},
    {"symbol":"AAOI","name":"Applied Optoelectronics","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"AXTI","name":"AXTI Inc","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"AMKR","name":"Amkor Technology, Inc.","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"ONTO","name":"Onto Innovation Inc.","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"CAMT","name":"Camtek Ltd.","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"KLIC","name":"Kulicke and Soffa Industries, Inc.","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"FORM","name":"FormFactor, Inc.","market":null,"theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"FN","name":"Fabrinet","market":"NYSE","theme":"AI","category":"Advanced Packaging Capex"},
    {"symbol":"TER","name":"Teradyne Inc","market":"NASDAQ","theme":"Robotics","category":"Robotics"},
    {"symbol":"KITT","name":"Nauticus Robotics","market":"NASDAQ","theme":"Robotics","category":"Robotics"},
    {"symbol":"TXN","name":"Texas Instruments","market":"NASDAQ","theme":"Robotics","category":"Robotics"},
    {"symbol":"ASTS","name":"AST SpaceMobile","market":"NASDAQ","theme":"Space","category":"Transport"},
    {"symbol":"RDW","name":"RedWire Corporation","market":"NASDAQ","theme":"Space","category":"Transport"},
    {"symbol":"RKLB","name":"Rocket Lab Corporation","market":"NASDAQ","theme":"Space","category":"Transport"},
    {"symbol":"SATL","name":"Satellogic Inc","market":"NASDAQ","theme":"Space","category":"Transport"},
    {"symbol":"LITE","name":"Lumentum Holdings Inc.","market":null,"theme":"Hardware","category":"Fiber Optics"},
    {"symbol":"CIEN","name":"Ciena Corporation","market":null,"theme":"Hardware","category":"Fiber Optics"},
    {"symbol":"VIAV","name":"Viavi Solutions Inc","market":null,"theme":"Hardware","category":"Fiber Optics"},
    {"symbol":"TSEM","name":"Tower Semiconductor Ltd.","market":null,"theme":"Hardware","category":"Fiber Optics"},
    {"symbol":"APH","name":"Amphenol Corporation","market":null,"theme":"Hardware","category":"Fiber Optics"},
    {"symbol":"VICR","name":"Vicor Corporation","market":null,"theme":"Hardware","category":"Fiber Optics"},
    {"symbol":"FCX","name":"Freeport-McMoRan Inc.","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"SCCO","name":"Southern Copper Corporation","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"TECK","name":"Teck Resources Limited","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"HBM","name":"Hudbay Minerals Inc.","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"ERO","name":"Ero Copper Corp.","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"TGB","name":"Taseko Mines Limited","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"BHP","name":"BHP Group Limited","market":null,"theme":"Metals","category":"Copper"},
    {"symbol":"AG","name":"First Majestic Silver Corp.","market":null,"theme":"Metals","category":"Silver"},
    {"symbol":"PAAS","name":"Pan American Silver Corp.","market":null,"theme":"Metals","category":"Silver"},
    {"symbol":"SVM","name":"Silvercorp Metals Inc","market":null,"theme":"Metals","category":"Silver"},
    {"symbol":"EXK","name":"Endeavour Silver Corp.","market":null,"theme":"Metals","category":"Silver"},
    {"symbol":"AEM","name":"Agnico Eagle Mines Limited’","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"AGI","name":"Alamos Gold Inc.","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"ARMN","name":"Aris Mining Corporation","market":"NASDAQ","theme":"Metals","category":"Gold"},
    {"symbol":"AU","name":"AngloGold","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"CDE","name":"Coeur Mining, Inc.","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"HYMC","name":"Hycroft Mining","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"GFI","name":"Gold Fields","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"KGC","name":"Kinross Gold","market":null,"theme":"Metals","category":"Gold"},
    {"symbol":"LLY","name":"Eli Lily and Co.","market":"NYSE","theme":"Pharmco","category":"Medicine"},
    {"symbol":"U","name":"Unity Software","market":"NYSE","theme":"Gaming","category":"Software"},
    {"symbol":"JOBY","name":"Joby Aviation","market":null,"theme":"Transportation","category":"Aviation"},
    {"symbol":"Salik","name":"Salik AE","market":null,"theme":"Transportation","category":"Aviation"},
    {"symbol":"ATI","name":"ATI","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"HWM","name":"Howmet Aerospace","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"GE","name":"GE Aerospace","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"LMT","name":"Lockheed Martin","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"RTX","name":"RTX","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"KTOS","name":"Kratos Defense & Security Solutions","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"KRMN","name":"Karman Holdings","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"EMBJ","name":"Embraer S.A.","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"FTAI","name":"FTAI Aviation Ltd","market":null,"theme":"Defense","category":"Defense"},
    {"symbol":"EQT","name":"EQT","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"KMI","name":"Kinder Morgan","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"STNG","name":"Scorpio Tankers Inc.","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"INSW","name":"International Seaways","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"FRO","name":"Frontline plc","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"WMB","name":"Williams Companies","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"PBR","name":"Petróleo Brasileiro S.A.","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"CVX","name":"Chevron Corporation","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"CVE","name":"Cenovus Energy","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"BP","name":"BP p.l.c.","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"VLO","name":"Valero Energy","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"PSX","name":"Phillips 66","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"MPC","name":"Marathon Petroleum","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"TDW","name":"Tidewater Inc","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"SLB","name":"SLB N.V","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"LBRT","name":"Liberty Energy Inc","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"HAL","name":"Halliburton Company","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"FTI","name":"TechnipFMC","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"BKR","name":"Baker Hughes","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"BORR","name":"Borr Drilling","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"NE","name":"Noble Corporation","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"RIG","name":"Transocean","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"XOM","name":"Exxon Mobil","market":null,"theme":"Energy","category":"Oil & Gas"},
    {"symbol":"ALNT","name":"Allient Inc.","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"BWXT","name":"BWX Technologies","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"NVT","name":"nVent Electric","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"POWL","name":"Powell Industries","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"SEI","name":"Solaris Energy Infrastructure","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"VRT","name":"Vertiv Holdings","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"ENS","name":"EnerSys","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"RRX","name":"Regal Rexnord Corporation","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"ETN","name":"Eaton Corporation","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"AME","name":"AMETEK","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"GTES","name":"Gates Industrial Corporation","market":null,"theme":"Energy","category":"Electrical-Power Equipment"},
    {"symbol":"GLW","name":"Corning Incorporated","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"CNGX","name":"CGX Energy","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"FN","name":"Fabrinet","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"JBL","name":"Jabil","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"CLS","name":"Celestica","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"TTMI","name":"TTM Technologies","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"FLEX","name":"Flex Ltd.","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"KN","name":"Knowles Corporation","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"DAKT","name":"Daktronics","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"CAMT","name":"Camtek Ltd.","market":null,"theme":"Energy","category":"Elec-Contract Mfg"},
    {"symbol":"TEX","name":"Terex Corporation","market":null,"theme":"Hardware","category":"Machinery"},
    {"symbol":"CAT","name":"Caterpillar Inc.","market":null,"theme":"Hardware","category":"Machinery"},
    {"symbol":"AGCO","name":"AGCO Corporation","market":null,"theme":"Hardware","category":"Machinery"},
    {"symbol":"ESE","name":"ESCO Technologies","market":null,"theme":"Hardware","category":"Machinery"},
    {"symbol":"FLS","name":"Flowserve","market":null,"theme":"Hardware","category":"Machinery"},
    {"symbol":"KNX","name":"Knight-Swift Transportation","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"ODFL","name":"Old Dominion Freight Line","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"XPO","name":"XPO, Inc","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"SAIA","name":"Saia, Inc","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"CHRW","name":"C.H. Robinson Worldwide","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"EXPD","name":"Expeditors International of Washington,","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"GXO","name":"GXO Logistics","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"JBHT","name":"J.B. Hunt Transport","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"FDX","name":"FedEx","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"ALGT","name":"Allegiant Travel Company","market":null,"theme":"Transportation","category":"Trucking"},
    {"symbol":"UUUU","name":"Energy Fuels Inc.","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"Processes monazite sand into high-purity Neodymium"},
    {"symbol":"MP","name":"MP Materials Corp","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"Extracting bastnäsite at Mountain Pass and vertically integrating into domestic NdFeB magnet manufacturing."},
    {"symbol":"ALOY","name":"REalloys Inc","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"Converting heavy rare earth oxides into defense-grade alloys and high-temperature metals like Samarium and Gadolinium"},
    {"symbol":"USAR","name":"USA Rare Earth","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"Process heavy rare earth elements and manufacture sintered NdFeB magnets"},
    {"symbol":"LYSDY","name":"Lynas Rare Earths","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"(Lynas Rare Earths Limited) - Only commercial producer of separated heavy rare earth elements outside of China."},
    {"symbol":"NEO","name":"Neo Performance Materials","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"They are the only Western company commercially producing the actual NdFeB magnetic powders and alloys at scale right now."},
    {"symbol":"ILU","name":"Iluka Resources Limited","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"(rare earths refinery): rare earths refinery for Australia"},
    {"symbol":"ARU","name":"Arafura Rare Earths Limited","market":null,"theme":"Robotics","category":"Magnet Metals","edge":"(ASX): \"Ore-to-oxide\" NdPr facility"},
    {"symbol":"ATI","name":"ATI Inc","market":null,"theme":"AI","category":"Structural Metallurgy","edge":"Dominant US producer of high-performance titanium and specialty alloys required for robotic joints."},
    {"symbol":"CRS","name":"Carpenter Technology","market":null,"theme":"AI","category":"Structural Metallurgy","edge":"US supplier of specialty structural alloys, including the high-strength steels, titanium, and magnetic"},
    {"symbol":"FCX","name":"Freeport-McMoRan","market":null,"theme":"AI","category":"Structural Metallurgy","edge":"World's largest producer of Molybdenum, which is strictly necessary for the structural steel in planetary roller screws"},
    {"symbol":"NB","name":"NioCorp Developments","market":null,"theme":"AI","category":"Structural Metallurgy","edge":"Critical pure-play company developing the Elk Creek project in Nebraska, aimed at supplying domestic Niobium, Scandium, and Titanium"},
    {"symbol":"MTRN","name":"Materion Corporation","market":null,"theme":"AI","category":"Structural Metallurgy","edge":"Major global processor of Beryllium"},
    {"symbol":"LGO","name":"Largo Inc.","market":null,"theme":"AI","category":"Structural Metallurgy","edge":"Leading publicly traded processors of Vanadium"},
    {"symbol":"BMM","name":"Blue Moon Metals","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Onshore supply and processing for like Germanium and Gallium"},
    {"symbol":"VNP","name":"5N Plus","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Gallium, Germanium, and Indium for advanced sensors and electronics"},
    {"symbol":"TECK","name":"Teck Resources","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Most significant producer of Germanium outside of China"},
    {"symbol":"ALB","name":"Albemarle Corporation","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Lithium extraction"},
    {"symbol":"EAF","name":"GrafTech International","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"High-purity Graphite for battery anodes"},
    {"symbol":"ALTM","name":"Arcadium Lithium","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Western lithium required to supply the batteries"},
    {"symbol":"SYR","name":"Syrah Resources Limited","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Balama mine for Graphite"},
    {"symbol":"FCX","name":"Freeport-McMoRan","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Humanoid requires up to 6.5 kilograms of copper"},
    {"symbol":"AW1(ASX)","name":"American West Metals","market":null,"theme":"AI","category":"Compute,Perception,Power","edge":"Advancing the West Desert project in Utah, for domestic geological sources for high-grade Gallium and Indium"},
    {"symbol":"SPY","name":"SPDR S&P 500 ETF Trust","market":"NYSE","theme":"ETFs","category":"Index"},
    {"symbol":"QQQ","name":"Invesco QQQ Trust","market":"NASDAQ","theme":"ETFs","category":"Tech Index"},
    {"symbol":"VOO","name":"Vanguard S&P 500 ETF","market":"NYSE","theme":"ETFs","category":"Index"},
    {"symbol":"VTI","name":"Vanguard Total Stock Market ETF","market":"NYSE","theme":"ETFs","category":"Broad Market"},
    {"symbol":"IWM","name":"iShares Russell 2000 ETF","market":"NYSE","theme":"ETFs","category":"Small Cap"},
    {"symbol":"EFA","name":"iShares MSCI EAFE ETF","market":"NYSE","theme":"ETFs","category":"International"},
    {"symbol":"VWO","name":"Vanguard FTSE Emerging Markets ETF","market":"NYSE","theme":"ETFs","category":"International"},
    {"symbol":"GLD","name":"SPDR Gold Shares","market":"NYSE","theme":"ETFs","category":"Commodity"},
    {"symbol":"TLT","name":"iShares 20+ Year Treasury Bond ETF","market":"NASDAQ","theme":"ETFs","category":"Bonds"},
    {"symbol":"AGG","name":"iShares Core U.S. Aggregate Bond ETF","market":"NYSE","theme":"ETFs","category":"Bonds"}
  ],
  "metals": [
    {"symbol":"XAU","name":"Gold","market":"Spot"},
    {"symbol":"XAG","name":"Silver","market":"Spot"},
    {"symbol":"XPT","name":"Platinum","market":"Spot"},
    {"symbol":"XPD","name":"Palladium","market":"Spot"},
    {"symbol":"COPPER","name":"Copper","market":"Spot"},
    {"symbol":"ALUM","name":"Aluminum","market":"Spot"},
    {"symbol":"NICKEL","name":"Nickel","market":"Spot"},
    {"symbol":"ZINC","name":"Zinc","market":"Spot"},
    {"symbol":"LEAD","name":"Lead","market":"Spot"},
    {"symbol":"LITH","name":"Lithium","market":"Spot"}
  ],
  "commodities": [
    {"symbol":"WTI","name":"WTI Crude Oil","market":"Futures"},
    {"symbol":"BRENT","name":"Brent Crude Oil","market":"Futures"},
    {"symbol":"NG","name":"Natural Gas","market":"Futures"},
    {"symbol":"CORN","name":"Corn","market":"Futures"},
    {"symbol":"SOYB","name":"Soybeans","market":"Futures"},
    {"symbol":"WHEAT","name":"Wheat","market":"Futures"},
    {"symbol":"COFFEE","name":"Coffee","market":"Futures"},
    {"symbol":"COTTON","name":"Cotton","market":"Futures"},
    {"symbol":"COCOA","name":"Cocoa","market":"Futures"},
    {"symbol":"SUGAR","name":"Sugar","market":"Futures"}
  ],
};

module.exports = { watchlistData };